import { Inter } from 'next/font/google';
import AnimationWrapper from './components/AnimationWrapper';
import './styles/globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Jucy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnimationWrapper>
        {children}
        </AnimationWrapper>

      </body>
    </html>
  );
}
