/* eslint-disable @next/next/no-page-custom-font */
import { Inter } from 'next/font/google';
import Preloader from './components/Preloader';
import AnimationWrapper from './components/AnimationWrapper';
import './styles/globals.css';
import Head from 'next/head';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Jucy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <link
          href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;700&display=swap"
          rel="stylesheet"/>
        </Head>
      <body className={inter.className}>
        {/* <Preloader /> */}
        <AnimationWrapper>
          {children}
        </AnimationWrapper>
      </body>
    </html>
  );
}
